apps/range-voting/app/src/components/NewProjectPanelContent.js, apps/range-voting/app/src/components/NewVotePanelContent.js, apps/range-voting/app/src/screens/Issues.js, apps/range-voting/app/src/screens/Overview.js
Newest FE updates, quite small, but not insignificant.
=> 65 issue management fe

apps/range-voting/contracts/RangeVoting.sol, apps/range-voting/test/range-voting.js, apps/shared/test-helpers/timeTravel.js
closes #23 and #69 
rebased from https://github.com/Giveth/planning-app/commit/f236150175ebb9219b4ce8938c3e80b47437d1b1
=> 23 implement can execute

apps/allocations/app/components/Card/Account.js, apps/allocations/app/components/Panel/NewAccount.js
Cleaned up accounts card per 169
=> 169 accounts ui fix

apps/allocations/app/components/Form/Input/AllocationTypeInput.js, apps/allocations/app/components/Form/Input/InputDropDown.js, apps/allocations/app/components/Panel/NewAllocation.js
=> 166 token transfer options

apps/allocations/app/components/App/App.js, apps/range-voting/app/App.js, apps/range-voting/app/components/Panels/VotePanelContent.js, apps/range-voting/app/script.js, apps/range-voting/app/utils/vote-settings.js, apps/range-voting/arapp.json, apps/range-voting/contracts/RangeVoting.sol
Isn't cleaned up completely but I'm moving on to getting the vote working then will circle back
=> 148 vote updates ui

apps/allocations/arapp.json, apps/range-voting/app/components/Panels/VotePanelContent.js, apps/range-voting/app/script.js, apps/range-voting/arapp.json, apps/range-voting/contracts/RangeVoting.sol
RV and allocations are connected now but the Dates field still needs to be fixed and the event sequencing isn't perfect. Need to connect the events from Allocations in Range Voting so that it triggers an update across apps.
=> 207 connect rv allocations

apps/allocations/app/components/App/App.js, apps/allocations/app/components/Card/Account.js, apps/allocations/app/components/Form/Field/FormField.js, apps/allocations/app/components/Form/Input/SettingsInput.js, apps/allocations/app/components/Shared/CheckBox.js, apps/projects/app/components/Card/RepoCard.js, apps/projects/app/components/Content/FilterBar.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/DropDown/DropDown.js, apps/range-voting/app/App.js, apps/range-voting/app/components/Panels/VotePanelContent.js, apps/range-voting/app/components/ProgressBar.js, apps/range-voting/app/components/VoteRow.js, apps/range-voting/app/components/VoteSummary.js, apps/range-voting/app/range-voting/RangeVoting.js, apps/shared/test-helpers/ganache-cli.sh
Each commit has its detailed info
Fixes #177
=> Replace hard coded theme colors by AragonUI equivalents, lints and style fixes 

.travis.yml, apps/allocations/contracts/Allocations.sol, apps/allocations/contracts/test/TestImports.sol, apps/allocations/test/allocations.test.js, apps/planning-app-kit/contracts/PlanningKit.sol, apps/planning-app-kit/package.json, apps/projects/contracts/Projects.sol, apps/range-voting/.solcover.js, apps/range-voting/contracts/RangeVoting.sol, apps/range-voting/contracts/test/TestImports.sol, apps/range-voting/contracts/test/mocks/ExecutionTarget.sol, apps/range-voting/contracts/test/mocks/RangeVotingMock.sol, apps/range-voting/test/range-voting.js, apps/range-voting/truffle.js, apps/shared/test-helpers/artifacts.js, apps/shared/test-helpers/contracts/apps/Voting.sol, apps/shared/test-helpers/package.json, package-lock.json
This PR addresses #215 and also involves some cleaning and changes to some imports in contracts and tests, also updates coverage configuration.
Detailed changes in each individual commit.
The failing tests were skipped by using `xit()` to gradually implement them without losing the green status in Travis.
The general rule of thumb should be from now preferring to avoid merging anything that breaks the CI and Coveralls badges passing status.
=> Fix Travis status to green

apps/allocations/contracts/Allocations.sol, apps/allocations/test/allocations.test.js, apps/projects/contracts/Projects.sol, apps/range-voting/test/range-voting.js, package-lock.json
I've reenabled some guards to get the tests passing and the contract performing safely in addition to updating the tests to work with the contract updates
=> allocations tests passing with guards

apps/allocations/package.json, apps/projects/package.json, apps/range-voting/package.json, future-apps/address-book/package.json, package-lock.json
Updates UI components in order to solve several problems and warnings happening in the browser DevTools.
Also adds missing modules to Projects App.
- rxjs-compat and babel-core seemed requirements to have the script running
- graphql-request is our minimal requirement to interact with Github API
Dependencies are tested and there were no conflicts found, script.js is working now.
=> Updates to UI module and missing packages in Projects

apps/allocations/contracts/Allocations.sol, apps/allocations/test/allocations.test.js, apps/projects/test/projects.test.js, apps/range-voting/test/range-voting.js, apps/shared/test-helpers/contracts/apps/AppProxyBase.sol, apps/shared/test-helpers/contracts/evmscript/EVMScriptRunner.sol, apps/shared/test-helpers/contracts/kernel/Kernel.sol, apps/shared/test-helpers/contracts/kernel/KernelConstants.sol, apps/shared/test-helpers/contracts/kernel/KernelProxy.sol, apps/shared/test-helpers/contracts/kernel/KernelStorage.sol, package-lock.json
The previous pull request still needed some work after merging with dev branch, there were some conflicts.
At some point the applied solution to the coverage build was not consistent, but I updated the involved Kernel and related contracts from AragonOS upstream and now it is fixed, and coverage green again.
=> Fix coverage

apps/projects/app/components/App/App.js, apps/projects/app/components/Panel/GithubAuth.js, apps/projects/app/components/Panel/NewProject.js, apps/projects/app/index.js, apps/projects/app/script.js
Work in progress.
Each individual commit has a detailed description of the changes and implementations.
=> [WIP] Projects v1 frontend

.gitignore, apps/address-book/contracts/AddressBook.sol, apps/allocations/app/components/Card/Account.js, apps/allocations/contracts/Allocations.sol, apps/range-voting/contracts/RangeVoting.sol
- I updated the dropdown options on the accounts card in allocations app - removed "manage parameters" and renamed "execute payout" to "distribute allocation" (#314)
- Updated some of the radspec @notice text (#287)
- Added DS_Store to gitignore
=> fixed some radspec, account dropdown, gitignore

apps/allocations/app/components/Card/Account.js, apps/projects/app/components/Card/Project.js
Those were basically the same problems, 346 and 398.
=> 346, 398 - truncation of long titles and descriptions in Cards

apps/projects/app/components/App/App.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Panel/NewBountyAllocation/NewBountyAllocation.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js, apps/projects/app/script.js, apps/projects/contracts/Projects.sol
Addresses #420 
All of the initial IPFS stuff is handled in this PR, from here the integration for the rest of the panels should mainly be copying these patterns and maybe massaging the data a little bit.
=> 420 - Initial RequestAssignment working

apps/planning-suite-kit/contracts/PlanningKit.sol, apps/projects/app/components/App/App.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/IssueDetail/IssueDetail.js, apps/projects/app/components/Content/IssueDetail/components/Detail.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js, apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js, apps/projects/app/script.js, apps/projects/arapp.json
=> 421 review applicant integration

apps/projects/app/components/App/App.js, apps/projects/app/components/Panel/SubmitWork/SubmitWork.js, apps/projects/app/script.js, apps/projects/contracts/Projects.sol, apps/projects/test/projects.test.js, apps/shared/test-helpers/contracts/lib/bounties/StandardBounties.sol
Had to make some modifications to the projects and standardBounties.sol contract to get this working. We definitely need to look into the other integration option for M5
=> 418 submit work integration

apps/projects/app/components/App/App.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/script.js, apps/projects/contracts/Projects.sol, apps/shared/json-abis/vault.json
Bounties contract address is showing now on settings screen, and minor related misc fixes #369
=> 369 bounty address

apps/planning-suite-kit/contracts/PlanningKit.sol, apps/projects/app/components/App/App.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js, apps/projects/app/script.js, apps/projects/arapp.json, apps/projects/package.json
=> 419 review work integration

apps/projects/app/components/Content/IssueDetail/components/Detail.js
=> View issue: change table border size (Solves #465)

apps/range-voting/app/components/ProgressBar.js, apps/range-voting/app/components/ProgressBarThick.js
=> Remove padding right to fill the bars completely at 100% (Solves #397)

apps/projects/contracts/Projects.sol
Updated various radspec messages for Projects contract (#494)
=> Update projects radpsec (#494)

apps/allocations/contracts/Allocations.sol, apps/allocations/test/allocations.test.js
- resolves #580
- resolves #616 
- resolves #305 
- resolves #216
=> 305 allocations contract redesign

apps/address-book/package.json, apps/allocations/app/components/App/App.js, apps/allocations/app/components/App/Payouts.js, apps/allocations/app/components/App/PayoutsTables.js, apps/allocations/app/components/App/index.js, apps/allocations/app/utils/helpers.js, apps/allocations/app/utils/mockData.js, apps/allocations/contracts/Allocations.sol, apps/allocations/package.json, apps/projects/package.json, apps/range-voting/package.json, apps/rewards/package.json, shared/ui/package.json
=> 615 payout tables

apps/projects/app/components/App/App.js, apps/projects/app/components/Content/FilterTile.js, apps/projects/app/components/Content/Filters.js, apps/projects/app/components/Content/IssueDetail/components/Detail.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js, apps/projects/app/components/Shared/FilterBar/FilterBar.js, apps/projects/app/components/Shared/FilterBar/FilterDropDown.js, apps/projects/app/components/Shared/FilterBar/index.js, apps/projects/app/components/Shared/FilterBar/prepareFilters.js, apps/projects/app/components/Shared/assets/components/IconX.js, apps/projects/app/script.js, apps/projects/package.json, package-lock.json
Combines the following PRs: #661, #701, #683 into a single branch/PR
=> Staging projects

apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/IssueDetail/components/Detail.js, apps/projects/app/components/Panel/NewBountyAllocation/NewBountyAllocation.js
Also disables multiple slot option in new bounty allocation cc @stellarmagnet 
#480
#697
=> 697 480 projects app panel

apps/projects/app/components/Card/Project.js
=> Project card: title limit: 2 lines, description: 5 lines

apps/address-book/app/components/App/Entities.js
Enhanced the address book entries
=> address book FE tweaks

apps/allocations/app/components/App/Accounts.js, apps/allocations/app/components/App/Payouts.js, apps/allocations/app/components/App/PayoutsTables.js, apps/allocations/app/components/Card/Account.js, apps/allocations/app/components/Form/Form.js, apps/allocations/app/components/Panel/NewAccount.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/contracts/Allocations.sol
I updated the styles and made the page responsive.
=> enhanced styles for allocations app

apps/allocations/app/store/events.js, apps/allocations/app/store/init.js, apps/allocations/app/store/token.js, apps/range-voting/app/Decisions.js
Fixes address book entries not loading in Range Voting and tokens not loading in allocations.
=> Hotfix dev errors

apps/projects/app/components/App/App.js
Before merging we must coordinate reconfiguring GitHub and redeploying Projects App.
=> new addresses for oauth services

apps/dot-voting/app/components/Panels/VotePanelContent.js, apps/dot-voting/app/components/ProgressBarThick.js
I've implemented this in a more generalized manner than was spec'd. This will display anytime a vote contains some form of token or ETH balance, instead of just if it's an allocation vote.
=> 855 Display candidate balance earned if a vote balance exists

apps/address-book/package.json, apps/allocations/package.json, apps/dot-voting/package.json, apps/projects/package.json, apps/rewards/package.json, package-lock.json
=> chore: bump parcel-bundler version

apps/address-book/package.json, apps/allocations/package.json, apps/dot-voting/package.json, apps/projects/package.json, apps/rewards/package.json, package-lock.json
Reverts AutarkLabs/planning-suite#866
This PR needs to be reverted because builds are currently failing when using the more recent version of parcel
=> Revert "chore: bump parcel-bundler version"

apps/projects/app/components/Content/Issues.js
=> 875 issues scroll fix

apps/rewards/app/components/App/App.js, apps/rewards/app/components/Content/MyRewards.js, apps/rewards/app/components/Content/Overview.js, apps/rewards/app/components/Panel/MyReward/MyReward.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/components/Panel/PanelManager.js, apps/rewards/app/components/Panel/ViewReward/ViewReward.js, shared/ui/components/form/inputs/InputDropDown.js
- resolve #887
- resolve #889
- fix number input box width issue that rendered incorrectly in firefox
=> 887 889 Rewards Fixes

apps/address-book/app/components/Panel/NewEntity.js
=> 684 Fix error message persisting at address book

package-lock.json, package.json
Please check and make sure that removing and regenerating the package-lock doesn't generate any changes before approving.
=> Regenerate package-lock file

apps/projects/app/App.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/utils/gql-queries.js
This is a proof of concept for a bot that posts bounty status updates to Github. Currently, the bot only posts updates when issues receive funding for the first time.
Things to consider:
* Doesn't include a URL since routing doesn't seem to be configured in the Planning Suite
* The comment is posted automatically using the account of the current user, rather than an independent (bot) account
=> Fund Issue Comments

docs/DEVELOPMENT_NOTES.md
Not sure about the right location for this though
=> Added troubleshooting for "Invalid Arg Type" error

apps/projects/app/utils/ipfs-helpers.js
We can start using our own IPFS gw for Projects.
=> configured Autark's VPS as IPFS gw for Projects

apps/projects/app/components/Content/IssueDetail/IssueDetail.js, apps/projects/app/components/Content/IssueDetail/Markdown.js, apps/projects/package.json
Fixes #955
This copies the Markdown setup from https://github.com/AutarkLabs/aragon-home/pull/16
=> Projects: use new Markdown styles

apps/address-book/.eslintrc
Fixes #938
This PR fixes one minor DX issue. From here, I suggest we improve Address Book by doing the following:
* [Address Book: find and remove dead code](https://github.com/AutarkLabs/planning-suite/issues/1090)
* [end-to-end testing](https://github.com/AutarkLabs/planning-suite/pull/861)
* [Address Book: address a11y issues found by react-axe](https://github.com/AutarkLabs/planning-suite/issues/1091)
* [Cleanup duplicated assets](https://github.com/AutarkLabs/planning-suite/issues/382)
* [Address Book: improve error handling / validation](https://github.com/AutarkLabs/planning-suite/issues/1093)
=> Address Book: frontend audit

docs/CODEOWNERS
This file can be used [by GitHub] and [by Pull Panda] to help streamline
our code review process.
[by GitHub]: https://help.github.com/en/articles/about-code-owners
[by Pull Panda]: https://docs.pullpanda.com/products/assigner
=> Add CODEOWNERS

docs/CODEOWNERS
I believe this improves the integration with Pull Panda
=> CODEOWNERS: use GitHub teams

apps/projects/.eslintrc.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Panel/NewIssue/NewIssue.js, apps/projects/app/components/Panel/NewIssueCuration/NewIssueCuration.js, apps/projects/app/components/Panel/NewProject/RepoSelector.js, apps/projects/app/store/helpers/issues.js, apps/projects/app/store/helpers/repos.js, apps/projects/app/store/helpers/tokens.js
See individual commits for more info.
These are two rules I think our code should follow. Our code didn't violate these rules in many places, so adding these rules was quick.
=> Projects: lint for eqeqeq and no-else-return

apps/projects/app/components/Panel/FundIssues/FundIssues.js
Address #1124 
Tested locally, apparently no errors or malfunction when disabling this code block
=> Temporarily disable comment on issue funding

apps/discussions/app/modules/Comment.js
After first click, show "Confirm delete" message. Only delete after clicking that.
=> Discussions/Comment: confirm delete

apps/rewards/.eslintrc.js, apps/rewards/app/components/Content/Overview.js, apps/rewards/app/components/Form/Field/FormField.js, apps/rewards/app/components/Panel/MyReward/MyReward.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/components/Panel/ViewReward/ViewReward.js, apps/rewards/app/script.js, apps/rewards/app/store/events.js, apps/rewards/app/store/token.js, apps/rewards/app/utils/helpers.js
Fixes #940
This PR improves our linter settings, which helped improve the code quality a little bit. Read the individual commit messages for details.
Beyond this, here's what I recommend doing next:
* [end-to-end testing](https://github.com/AutarkLabs/planning-suite/pull/861)
* [Rewards: address a11y issues found by react-axe](https://github.com/AutarkLabs/planning-suite/issues/1105)
=> Rewards: frontend audit

apps/discussions/arapp.json, apps/discussions/contracts/DiscussionApp.sol, apps/planning-suite-kit/contracts/PlanningKit.sol
- This is apparently needed to be considered an actual Aragon app by the Kernel
- Reference: https://hack.aragon.org/docs/cli-dao-commands#dao-install
> In aragonOS an app is considered to be installed in a DAO if it uses the DAO Kernel as its Kernel and there are references to the app in the ACL of the DAO.
=> Add a minimal EMPTY_ROLE to Discussions

apps/dot-voting/app/components/VoteDetails/index.js, apps/rewards/app/components/App/App.js, apps/rewards/app/components/Panel/NewReward/NewReward.js
This PR makes Rewards work in newstyle branch. Updated are Dropdowns and Header - there was no conversion of classes, no hooks have been added.
=> upgrade Rewards ADS UI

apps/address-book/package.json, apps/allocations/app/components/Form/Input/AddressDropDown.js, apps/allocations/package.json, apps/dot-voting/package.json, apps/rewards/package.json
This PR is for: patch version upgrade of Aragon UI, which fixes Cards, and b) small DropDown fix in Allocations.
=> Aragon ui fixes

apps/address-book/app/components/App/Entities.js
=> Icon for the delete entry in the context menu

apps/address-book/app/components/App/App.js, apps/address-book/app/components/App/Entities.js, shared/identity/LocalIdentityBadge.js
1. Change list layout so that it corresponds with the design.
Before: 
After: 
Mobile version:
2. Don't show Header if there are no contacts.
Before:
After:
See previous conversation [here](https://github.com/AutarkLabs/open-enterprise/pull/1194).
=> Addressbook design check

apps/dot-voting/app/api-react.js
Comparing the data in this stub to a logged `appState` from App.js revealed some inconsistencies.
=> Dot Voting/api-react: more closely mirror actual

apps/discussions/README.md, apps/dot-voting/arapp.json, apps/dot-voting/contracts/DotVoting.sol, apps/dot-voting/test/DotVoting.test.js, apps/planning-suite-kit/contracts/PlanningKit.sol, apps/shared/test-helpers/contracts/apps/Voting.sol, docs/GETTING_STARTED.md, kits/planning-suite/README.md, kits/planning-suite/contracts/PlanningSuite.sol, kits/planning-suite/test/planning-suite.test.js
Creating this PR on behalf of @Quazia. It's in progress, but a PR helps with visibility.
=> Dot voting/gas hot fix

apps/address-book/app/api-react.js, apps/address-book/app/components/App/App.js, apps/address-book/app/components/Panel/NewEntity.js
Fixes #1173 
Please note that this fix doesn't follow the designs in terms of error validation. The reason is because I don't know if @rkzel is doing that already or not.
=> Address book: Duplicate address error

apps/address-book/app/index.html, apps/allocations/app/index.html, apps/discussions/app/index.html, apps/dot-voting/app/index.html, apps/projects/app/index.html, apps/rewards/app/index.html
This sets up our apps to work more consistently between frontend-only mode and full within-the-client mode.
=> Standardize index.html files; add device-width tag

apps/address-book/package.json, apps/allocations/package.json, apps/dot-voting/package.json, apps/planning-suite-kit/package.json, apps/projects/package.json, apps/rewards/package.json
Browser list inside package.json have been set to the same as [aragon apps](https://github.com/aragon/aragon-apps/blob/102b85e6d986d2106ada9b0d81c6cd0ba051571b/apps/finance/app/package.json#L55).
=> Configure browserlist (#923)

apps/address-book/app/components/App/App.js, apps/address-book/app/components/App/Entities.js, apps/address-book/app/components/LocalIdentityBadge/IdentityManager.js, apps/address-book/app/components/LocalIdentityBadge/LocalIdentityBadge.js, apps/address-book/app/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js, apps/address-book/app/components/LocalIdentityBadge/LocalLabelPopoverTitle.js, apps/address-book/package.json
=> Address Book: ugrade AragonUI to 1.0.0-alpha.26

apps/projects/app/components/Content/IssueDetail/EventsCard.js
We need a `user` key on all items in the history
=> Projects: fix EventsCard

apps/projects/app/components/Card/Issue.js
* don't add onClick to div
* only link title
* add something useful to the hash, so the user has an idea of what will happen when they click this item
* since onClick on the entire card is no longer present, the context menu works again 🎉
=> Projects: only link Issue title to detail page

apps/projects/app/components/Content/IssueDetail/EventsCard.js, apps/projects/app/components/Content/IssueDetail/StatusCard.js, apps/projects/app/components/Content/IssueDetail/index.js, apps/projects/app/components/Form/Form.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js, apps/projects/app/components/Shared/BountyContextMenu.js, apps/projects/app/store/helpers/issues.js, apps/projects/app/utils/bounty-status.js
There were some missing details from Funding Panel while saving onto IPFS.
Activity tab looks better, and started to display working action buttons (Request Assignment).
=> Activity tab improved, IPFS data enriched

apps/rewards/contracts/Rewards.sol
Somehow theses changes got overwritten and were never in the `web3/rewards` branch
=> Restore Rewards audit changes

apps/rewards/contracts/Rewards.sol
- Added _ to private functions
- Removed some comments
=> Final small Rewards tweaks

apps/projects/app/App.js, apps/projects/app/components/Card/Project.js, apps/projects/app/components/Content/IssueDetail/DetailsCard.js, apps/projects/app/components/Content/IssueDetail/EventsCard.js, apps/projects/app/components/Content/IssueDetail/StatusCard.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/Form/Field/FieldTitle.js, apps/projects/app/components/Form/Field/FormField.js, apps/projects/app/components/Panel/NewIssueCuration/NewIssueCuration.js, apps/projects/app/components/Panel/PanelComponents.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js, apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js, apps/projects/app/components/Panel/SubmitWork/SubmitWork.js
This fixes most of UI/UX issues. What is not yet addressed: FilterBar searchbox being focused when it should not be and borders of dropdowns.
=> post-review fixes

apps/allocations/app/components/App/Budgets.js
Fixes a style regression introduced in #1313
=> Allocations: add bottom margin to Budgets list

apps/allocations/app/components/Panel/NewBudget.js
Started using AragonUI's `Field` element instead of our own `FormField`.
=> Allocations: improved labels colors in New Allocation side panel

apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/IssueDetail/DetailsCard.js
For a moment deadline was passed in form of a timestamp. Now it's back to proper date.
=> fixed timeout display in IssueDetail and list

apps/dot-voting/app/components/VoteDetails/CastVote.js
=> Dot Voting: add an address badge to the "cast vote" card

apps/address-book/manifest.json, apps/allocations/manifest.json, apps/dot-voting/manifest.json, apps/projects/manifest.json, apps/rewards/manifest.json
This PR includes updates to the `manifest.json` for each Open Enterprise app to have more succinct app descriptions.
=> App description changes

apps/projects/app/components/Shared/FilterBar/FilterBar.js
Resolves: "Issue Search on mobile only lets me input one character at a time, and then I have to click again on the search area to insert another character."
=> Search popover on mobile refocuses as text is entered

apps/projects/app/components/Panel/FundIssues/FundIssues.js
Fixes #1371 
Tested on Chromium and Firefox.
=> Projects: truncate issue title in fund issue panel

apps/projects/app/api-react.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Shared/BountyContextMenu.js, apps/projects/app/components/Shared/NumberInput.js, apps/projects/app/store/helpers/settings.js
* Can be Hourly or Fixed
* When Fixed, hide Base Rate field
* Store this value by setting Base Rate to 0
* Add fundingModel attribute to bountySettings in appState
See commit messages for full details. You'll see that in my first commit, I improved the styling to make it easier to add this new field. Here's what it looks like:
=> Projects/Settings: Add Funding Model option

apps/projects/app/hooks/useShapedIssue.js
* `appState.bountyIssues` is not defined; change reference to `appState.issues`
* rename `bountyIssueObj` to `bounties` and `tokenObj` to `tokens`; memoize them based on appState values
* remove variable `expLevels`, which is only used once
* rename `bountyId` to `bounty`
=> Projects/useShapedIssue: fix bug; clean up

apps/rewards/app/app-state-reducer.js, apps/rewards/app/components/App/App.js, apps/rewards/app/components/Card/Empty.js, apps/rewards/app/components/Content/MyRewards.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/components/Panel/RewardSummary.js
Removed console.logs, solved a warning and put explicit props in App.
=> Rewards: miscellaneous cleanup

apps/address-book/app/components/App/Entities.js, apps/address-book/app/components/Panel/NewEntity.js
Fixes #1412 
Uses AragonUI's theme for setting the colors of the type badges
Removes the "Project" type
=> Address Book: update type badges colors

apps/dot-voting/app/store/votes.js
=> Dot Voting: add missing titles in issue curation

templates/open-enterprise/contracts/BaseOEApps.sol
Add candidate options should be assigned to Voting, not Tokens.
=> Updated Dot Voting permission in template

apps/rewards/app/utils/metric-utils.js
=> Rewards: solved infinite monthly average bug

apps/rewards/app/app-state-reducer.js, apps/rewards/app/components/Content/MyRewards.js, apps/rewards/app/utils/constants.js, apps/rewards/app/utils/helpers.js
*TO DO*: wait for #1425 to be merged, then redirect this PR to `dev` and merge
Fixes #1409 
Before:
After:
=> Rewards: improve decimal rounding in My Rewards

apps/rewards/app/components/Panel/NewReward/NewReward.js
=> Rewards: solved disbursement frequency bug & allowed single-disbursement recurring dividends

apps/rewards/app/components/App/App.js, apps/rewards/app/components/Content/MyRewards.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/utils/helpers.js
**TODO**: 
Fixes a MiniMe token validation bug that didn't recognize MiniMe tokens as such.
Before:
After:
**This PR was only tested with the DAO's token in a local environment. It definitely needs more testing.**
=> Rewards: solved MiniMe validation bug

apps/projects/app/App.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Content/IssueDetail/EventsCard.js, apps/projects/app/components/Content/IssueDetail/index.js, apps/projects/app/utils/gql-queries.js
This solves the following problem:
* Go to an Issue Detail page
* Add funding (or take some other bounty-related action)
* Issue does not update to show the new bounty-related data
It solves this by virtue of the fact that `shapeIssue` relies on `useAragonApi`, and will be recalculated (and in turn reshape the issue) when bounty data is updated.
=> Projects/IssueDetail: use issueId, not issue

docs/GETTING_STARTED.md
* Added missing roles for the template
* Renamed from That Planning Suite to Open Enterprise
* Changed apm repo names
* Updated initialization params
=> Updated docs based on new permissions and params

apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Panel/PanelComponents.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js
Reduced the font size of title and made them truncate with ellipses. Removed the repo name/issue link from FundIssue. Fix some css on HoursInput in RequestAssignment panel.
=> Projects: Truncating panel issue titles to fit one line

apps/allocations/app/components/App/AllocationsHistory.js
=> Allocations: set a fixed width for recipients container

apps/rewards/app/components/Content/MyRewards.js, apps/rewards/app/components/Panel/NewReward/NewReward.js
=> Remove `toDate` from the multi-instance reward logic branch

apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js, apps/projects/app/components/Panel/usePanelManagement.js, apps/projects/app/components/Shared/BountyContextMenu.js, apps/projects/contracts/Projects.sol
Fixes #1439 
Before:
After:
Also removed a linting issue from FundIssues.js
=> Projects: "Submit application" instead of "Request Assignment"

apps/address-book/app/components/App/Entities.js, apps/address-book/app/components/Panel/NewEntity.js
Fixes #1173, again
Also removed some PropType validation warnings from Entities.js
=> Address Book: disallow duplicate addresses

apps/projects/app/components/Shared/FilterBar/FilterBar.js, apps/projects/app/components/Shared/FilterBar/FilterDropDown.js, apps/projects/app/components/Shared/FilterBar/prepareFilters.js
Split FilterDropDown into FDD and Overflow components. Also, fixed padding in items lists and added very light grey as background color to artificial "labelless" and "milestoneless" items.
=> Minor FilterBar UI fixes

apps/projects/app/components/Content/IssueDetail/StatusCard.js, apps/projects/app/components/Shared/BountyContextMenu.js
As per the ticket, I added (restored) "submit application" item to Issues Bounty Context Menu. Screenshot attached (that blue border is not usually visible):
=> updated BountyContextMenu

apps/shared/test-helpers/mine.js, package.json
As a small exercise I rewrote the mine macro script (for testing and other useful little stuff) to be usable with `truffle exec`
=> Enhance the mine cli script to be usable with Truffle

apps/rewards/app/components/App/App.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/store/token.js, apps/rewards/app/utils/token-utils.js
=> Rewards: allow past dates after reference asset creation

apps/address-book/app/components/Card/Empty.js
=> Address Book: added disclaimer for identity provider

apps/shared/test-helpers/contracts/apps/Voting.sol
- A support vote is no longer automatically cast when a vote is created
=> Update "Create vote" notice

apps/dot-voting/app/components/VoteDetails/CastVote/CastVote.js
Fix for issue #1561 
Before:
After:
=> Added preventDefault to submit function

apps/rewards/app/components/Form/Field/FormField.js, apps/rewards/app/components/Panel/NewReward/NewReward.js
Removed some console warnings about props, and some error validation issues.
=> Rewards: some minor bug fixes

apps/rewards/app/components/App/App.js, apps/rewards/app/components/Panel/NewReward/NewReward.js, apps/rewards/app/components/Panel/RewardSummary.js
**TO DO before merging**
Related to #1526
=> Rewards: add block numbers to New Reward summary

apps/rewards/app/components/Panel/NewReward/NewReward.js
Fixes #1554
Added 1 new error, modified a warning and added 2 new warnings. The blue info box now acts as a warning message, i.e. it is displayed on input validation along with other errors.
---
---
---
=> Rewards: Frequency validation

apps/projects/app/components/Panel/FundIssues/FundIssues.js
Fixes #1552
* When funding mode is "Fixed": check all vault funds before displaying "No Funds" message
* When funding mode is "Hourly": check only configured funding token
=> Projects/FundIssues: check all vault funds

apps/rewards/app/utils/token-utils.js
This handler was merged in after the fixes were applied to the other minime getter functions, but this has been tested now both locally and in staging
=> Add creation date try/catch block

apps/projects/app/components/Panel/SubmitWork/SubmitWork.js, apps/projects/app/components/Shared/BountyContextMenu.js
- Changed a string instance of "proof of work" to submission
- Disabled the update button for the Projects context menu
=> Projects quick-fixes

apps/dot-voting/app/api-react.js, apps/dot-voting/app/components/VoteDetails/index.js, apps/dot-voting/app/store/votes.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/store/helpers/tokens.js, apps/rewards/app/store/init.js, apps/rewards/app/store/token.js, apps/rewards/app/utils/token-utils.js, shared/abi/token-decimals256.json, shared/lib/token-utils.js, shared/store-utils/token.js
Dai utilizes a token contract that is not ERC20-compliant. This PR ensures that all token handling in Projects and Rewards utilizes the shared handlers, which were written to accommodate the DSToken contract developed for Dai by Dapphub. In addition to registering the mainnet DAI address in our apps, our handlers now also can handle any unknown instances of this contract that a DAO may interact with.
=> feat: Handle DAI in OE Apps

apps/address-book/public/meta/details.md, apps/allocations/public/meta/details.md, apps/dot-voting/manifest.json, apps/dot-voting/public/meta/details.md, apps/projects/public/meta/details.md, apps/rewards/public/meta/details.md
Before, our details.md file was just a placeholder. I populated it with valid content.
I also updated the app description for Dot Voting.
=> Added details.md for all OE apps

apps/address-book/arapp.json
=> Address Book/arapp: change entry into entity

apps/projects/app/components/Panel/FundIssues/EditBounty.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/components/Panel/FundIssues/styled.js
Fixes #1605
I recommend looking at changes [with whitespace turned off](https://github.com/AutarkLabs/open-enterprise/pull/1637/files?w=1).
See individual commits for more info.
=> Projects/FundIssues: clean up

apps/rewards/app/components/Content/Overview.js
=> Rewards/Overview: add block number to "next payout"

apps/rewards/app/components/Content/MyRewards.js
Fixes #1627
**Note**: I couldn't find the double check icon in AragonUI. I used
the circled check instead.
=> Rewards/My Rewards: add icons to "status"

apps/projects/app/api-react.js, apps/projects/app/components/Content/IssueDetail/index.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/context/DecoratedRepos.js, apps/projects/app/hooks/useShapedIssue.js
* import custom `api-react`
* set `isSyncing: false`
* use `INITIAL_STATE.github`, which includes `scope` now
=> Projects: fix frontend stub

apps/dot-voting/app/components/VoteDetails/Label.js
=> Dot Voting: Fix Label color

apps/rewards/app/utils/helpers.js
**TODO before merging**:
Fixes #1628
**Note:** We need to standardize date formats.
=> Rewards/MyRewards: add date to claimed status

apps/rewards/app/components/Panel/NewReward/NewReward.js
=> Rewards/NewReward: improve error message for non-transferable assets

apps/address-book/app/components/App/App.js, apps/address-book/app/components/Panel/NewEntity.js, apps/allocations/app/components/Card/Budget.js, apps/dot-voting/app/components/Panels/NewPayoutVotePanelContent.js, apps/dot-voting/app/components/VoteDetails/CastVote/CastVote.js, apps/dot-voting/app/components/VoteDetails/VoteEnact.js, apps/projects/app/App.js, apps/projects/app/components/Card/Project.js, apps/projects/app/components/Content/IssueDetail/EventsCard.js, apps/projects/app/components/Content/IssueDetail/StatusCard.js, apps/projects/app/components/Content/Settings.js, apps/projects/app/components/Panel/PanelManager.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js, apps/projects/app/components/Panel/usePanelManagement.js, apps/projects/app/components/Shared/BountyContextMenu.js, apps/rewards/app/components/Panel/PanelManager.js, shared/ui/components/form/inputs/RecipientsInput.js
1. Needed to add it excplicitly to usePanelManagement
(because default titles come directly from panel's filename),
Application View Panel header:
Work View Panel (header and buttons):
2. Also fixed BountyContextMenu - added viewing work and
assignment options as per spec,
Application submitted:
Work submitted:
3. Also fixed ReviewWork panel - reject/accept buttons didn't
show icons (that was caused by Aragon UI update I guess)
=> Changed all 'Review' texts to 'View'

apps/dot-voting/app/components/VotingCard.js
=> Dot Voting: Fix badge color

apps/projects/app/components/Content/Settings.js
Removed difficulty modifiers from the fixed funding model and added remove buttons to both fixed and hourly.
=> Projects: Removed difficulty modifier from Fixed funding model

apps/projects/app/components/Shared/BountyContextMenu.js
=> Projects: Only display 'Submit Application' before deadline

apps/projects/app/api-react.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Form/Form.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js, apps/projects/app/store/helpers/issues.js
In order to see more clearly the input data that addBounties expects and the way Projects expects the resulting data to be shaped, I have added `addBounties` to the api-react stub.
Doing this raised some interesting questions! I've investigated these questions and updated the code correspondingly. See individual commit messages for more info.
=> Projects: stub addBounties; fix questions raised

apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
Original request slightly changed:
This is the almost correct version, the final version has lighter grey color of the dates. Also, the change was made to both review panels - Work and Application.
=> display review date in ReviewWork and ReviewApplication Panels

apps/allocations/app/api-react.js
* set `budgets`, instead of `accounts`, since appStateReducer is not run properly in this environment (why??)
* comment out `allocations` in initialState
* add `tokens` to initialState
* update data structure set by newAccount
=> Allocations/api-react: fix newAccount

apps/allocations/app/api-react.js, apps/allocations/app/components/App/App.js, apps/allocations/app/components/App/Budgets.js, apps/allocations/app/components/App/Overview.js, apps/allocations/app/components/App/index.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/app/components/Panel/NewBudget.js, apps/allocations/app/context/Panel.js, apps/allocations/app/index.js
This lays the groundwork for adding routing.
We want everything in the new Overview component to be displayed on the home page, whereas the stuff that's still in App.js is useful for all pages.
=> Allocations: clean up App.js

apps/rewards/app/utils/constants.js
=> Rewards/Overview: uppercased type

shared/integrations/token-manager-custom/contracts/TokenManager.sol, shared/integrations/whitelist-oracle/contracts/WhitelistOracle.sol, templates/open-enterprise/.solcover.js, templates/open-enterprise/contracts/BaseTemplate.sol, templates/open-enterprise/temp/helpers/apps.js, templates/open-enterprise/temp/scripts/test-ganache.sh
These changes allow for multiple token options when creating a new DAO
First token options:
- Shareholder
- Membership
- Reputation
Second token option:
- Reputation
Also,
- Can set either the first or second token to be in control of Voting and/or Dot Voting
- The Reputation tokens use WhitelistOracle to control who can transfer tokens
=> [WIP] Reputation template

apps/projects/app/components/Panel/FundIssues/EditBounty.js, apps/projects/app/components/Panel/FundIssues/FundIssues.js
Fixes issues in #1591
Accidentally branched off of `projects-contextmenu` and PR #1669
=> Projects: Switch from issues to bountylessIssues

apps/rewards/app/components/Panel/NewReward/NewReward.js
=> Rewards/NewReward: rename "reference asset" to "reference token"

apps/address-book/package.json, apps/allocations/app/api-react.js, apps/allocations/app/components/App/AllocationsHistory.js, apps/allocations/app/components/App/App.js, apps/allocations/app/components/App/BudgetDetail.js, apps/allocations/app/components/App/Budgets.js, apps/allocations/app/components/App/Overview.js, apps/allocations/app/components/App/index.js, apps/allocations/app/components/BudgetContextMenu.js, apps/allocations/app/components/Card/Budget.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/app/components/Panel/NewBudget.js, apps/allocations/app/context/Panel.js, apps/allocations/app/hooks/usePathHelpers.js, apps/allocations/app/hooks/useSaveBudget.js, apps/allocations/app/store/events.js, apps/allocations/app/utils/prop-types.js, apps/allocations/package.json, apps/discussions/package.json, apps/dot-voting/package.json, apps/projects/package.json, apps/rewards/package.json, shared/api-react/index.js
Fixes #1575 
A lot changed to support this. If you have questions about specific changes, you can check individual commits & commit messages, which are quite detailed. 
There's a bit in `Card/Budget.js` where indentation changed. To hide this noise, view the diff [with indentation changes hidden](https://github.com/AutarkLabs/open-enterprise/pull/1758/files?w=1).
=> Allocations: add Budget Detail page

apps/allocations/app/components/App/BudgetDetail.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/app/utils/helpers.js
Fixes the form fields, the available funds message, and provide a help dialog. ~When the `budget-details` branch get merged I will redirect this to `dev`~
=> Allocations: New allocations panel

apps/allocations/app/components/App/App.js, apps/allocations/app/components/App/Budgets.js, apps/allocations/app/components/App/Overview.js, apps/allocations/app/components/Card/Empty.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/app/context/Panel.js
fixes #1642 
Read individual commit messages for more context on specific changes
I recommend reading the diff [with indentation changes hidden](https://github.com/AutarkLabs/open-enterprise/pull/1772/files?w=1)
=> Allocations: add budget filtering; change buttons

apps/allocations/app/components/Panel/NewBudget.js
~When the `budget-detail` branch (PR #1758) gets merged I'll redirect this to `dev`~
Small visual changes to the panel:
And here it shows weeks if the number of days is a multiple of 7:
=> Allocations: New Budget panel

apps/address-book/app/components/App/App.js, apps/address-book/app/components/Panel/NewEntity.js
Very small a11y improvement. No visible UI changes.
=> Added main section and description of input fields

apps/projects/app/App.js, apps/projects/app/api-react.js, apps/projects/app/components/Card/Issue.js, apps/projects/app/components/Card/Project.js, apps/projects/app/components/Content/Issues.js, apps/projects/app/components/Content/Overview.js, apps/projects/app/hooks/usePathSegments.js
Current status:
Deep linking implemented for:
=> Projects deep links implementation

apps/dot-voting/app/App.js, apps/dot-voting/app/Decisions.js, apps/dot-voting/app/app-logic.js, apps/dot-voting/app/index.js, apps/dot-voting/package.json
Deep linking for Dot Voting. Uses app-logic.js to handle the path and parse the the voteId.
=> Dot Voting: Implement deep linking

apps/allocations/app/app-state-reducer.js, apps/allocations/app/components/App/AllocationsHistory.js, apps/allocations/app/components/App/Payouts.js, apps/allocations/app/components/Card/Budget.js, apps/allocations/app/components/Panel/NewAllocation.js, apps/allocations/app/utils/helpers.js, shared/ui/constants.js, shared/ui/helpers.js
Reverts AutarkLabs/open-enterprise#1787
=> Revert "Allocation: add support for tokens with different decimal amounts"

apps/projects/app/components/Content/IssueDetail/EventsCard.js, apps/projects/app/components/Panel/ReviewWork/ReviewWork.js, apps/projects/app/components/Panel/usePanelManagement.js
As per issue 1818. It was added (transplanted) from very similar Application Review Panel:
And the second submission, still unreviewed:
=> fix: Work Panel was unable to show multiple submissions

apps/dot-voting/app/App.js, apps/dot-voting/app/Decisions.js, apps/dot-voting/app/components/Panels/NewVote.js, apps/dot-voting/app/components/Panels/index.js, apps/dot-voting/app/components/VoteDetails/VotingResults.js, apps/dot-voting/app/components/VoteStatus.js, apps/dot-voting/app/components/VotingOption.js, apps/dot-voting/app/store/votes.js, apps/dot-voting/app/utils/vote-utils.js, apps/dot-voting/package.json, shared/ui/components/form/Form.js, shared/ui/components/form/index.js, shared/ui/components/form/inputs/OptionsInput.js, shared/ui/components/form/inputs/RecipientsInput.js
The PR adds informative dot voting to the Dot Voting app. It covers everything in this epic: https://github.com/AutarkLabs/product/issues/48
Just a note, in the gif it shows the error message: 'Options may not be identical' but it has been updated to 'The same option cannot be specified twice.'
=> feat: informative dot votes
