AutarkLabs/open-enterprise

- apps/range-voting/contracts/RangeVoting.sol
- apps/range-voting/test/mocks/ExecutionTarget.sol
- apps/range-voting/test/range-voting.js
Pull request fixes issue with returning array of strings in functions, and implements `getVote` & `getVoterState` functions for issue #24. Tests for `getVote` & `getVoterState` functions yet to be implemented in `range-voting.sol`.
Added carrot before pragma version in `ExecutionTarget.sol`
Changes in RangeVoting.sol
* Changed `candidateKeys` from type string[] to bytes32[]
* Implemented `getVote` & `getVoterState` functions
Changes in range-voting.js
* Changed all empty tests to pending
> Fixed 'candidateKeys'; Implemented 'getVote' & 'getVoterState' functions

- apps/allocations/arapp.json
- apps/range-voting/app/components/Panels/VotePanelContent.js
- apps/range-voting/app/components/Slider.js
- apps/range-voting/arapp.json
Each change is detailed in the individual commit.
Closes #203 
Workaround for #205 
I couldn't manage to customize AragonUI default Slider, so I needed to override the component to define custom width and align the handle and the bar to their parent container
> Tweak styles in Range Voting, Slider UI and others.

- apps/range-voting/contracts/RangeVoting.sol
- apps/range-voting/test/range-voting.js
More resolutions for #185
- Adds previously missing assert statements
- Fixes typos in notices
- Increases test coverage
Notes:
- Still need to address TODO's
- Consider replacing getters in tests with event catchers (unless the test itself is testing a getter method)
- 2 lines of uncovered contract code remaining
Otherwise, PR is candidate for "fast-track".
> 185 range-voting contract tests

- apps/projects/contracts/Projects.sol
- apps/projects/test/projects.test.js
The Projects contract now accepts an array of repoIds, so each issue can originate from a different repo, as long as all repos have already been added to the contract.
> multi-repo bounties passing contract tests

- README.md
- apps/projects/app/components/App/App.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/script.js
- apps/projects/contracts/Projects.sol
- apps/projects/test/projects.test.js
The following is addressed in this PR:
- Projects contract test coverage expanded (#413)
- All submmissions are now exposed in the frontend, and contain the Ethereum address of the submitter
- Feedback can now be submitted to the contractvia a new  IPFS hash in `approveAssignment` and `reviewSubmission` that contains both the initial information and the feedback. (#472) Currently in the frontend the pre-existing IPFS hash is resubmitted until further enhancements are made to the frontend  to expose this feedback to the users.
> 472 issue detail feedback

- apps/projects/contracts/Projects.sol
- apps/projects/test/projects.test.js
This solution is constant-time in that it ensures the index of the repo in question does not exceed the repoIndex array length before attempting to access it.
I also added 3 test cases with a repo array length of 3 to ensure correct behavior regardless of which array position is removed.
> 907 Resolve repoIndex out-of-bounds revert

- apps/projects/app/components/Shared/BountyContextMenu.js
Fixes #934 
[Requirements]:
in the past, display a “View Funding Proposal” action in the issue’s
context menu.
the context meny of the Issue Detail page.
status (it sholuld be included for fulfilled bounties)
Other things that snuck into this change:
- Remove the `ActionLabel` component, which only added some spacing to
the left of items. This spacing is no longer wanted.
- Create a new `Item` styled component which wraps `ContextMenuItem` and
allows adding a `bordered` property which adds a top border. This
border provides visual separation between groups of menu items.
Here's an example of what this action menu looks like now:
- My `prettier` auto-runs on save, and reformatted some code (adding
trailing commas and adjusting line lengths here andd there.)
You'll see that the …
> View Funding Proposal action button

- apps/projects/app/components/Content/Issues.js
Fixes #901
This matches the behavior of GitHub, searching for exact strings rather than using regex. This means that searching for `*` will only match issues that actually have a `*` character in their title, rather than trying to construct an invalid regex (which caused an error, previously).
> Projects: Search exact text, not regex

- apps/projects/app/App.js
- apps/projects/app/components/Card/Issue.js
- apps/projects/app/components/Content/IssueDetail/IssueDetail.js
- apps/projects/app/components/Content/Issues.js
- apps/projects/app/components/Panel/PanelManager.js
- apps/projects/app/components/Panel/ViewFunding/Issue.js
- apps/projects/app/components/Panel/ViewFunding/ViewFunding.js
- apps/projects/app/components/Panel/ViewFunding/index.js
- apps/projects/app/components/Shared/BountyContextMenu.js
Fixes https://github.com/AutarkLabs/planning-suite/issues/931
When viewing a funding proposal,
This panel must have the following details (see design mockup below):
- Approved
- Rejected
- If there are multiple currencies, have a dot between them and list in alphabetical order and up to 2 decimal places
- 400 ANT  •  50 DAI  •  0.23 ETH
- The number of issues being funded
- Repo name
- issue number
- Issue name
- Estimated time
- Experience level
- Deadline
- “Due in…” - follow same format as Projects Issue List
- Funding Amount
From https://projects.invisionapp.com/d/main#/console/17635937/365601746/preview
> Add Funding Side Panel

- apps/planning-suite-kit/contracts/PlanningKit.sol
- apps/projects/arapp.json
- apps/projects/contracts/Projects.sol
- apps/projects/test/projects.test.js
- apps/shared/test-helpers/contracts/lib/bounties/StandardBounties.sol
- package.json
fixes #926 
* I had an issue with the refund functionality. As @Quazia helped me figure out, the StandardBounties contract was trying to refund the Projects contract, instead of the actual user. This could work in such a way, that the Projects contract is refunded and then refunds the user. Even though that might be the cleanest option, it requires knowledge about `AragonApp` contracts that I currently don't possess. Instead, I modified the StandardBounties contract so that a `refundee` address can be specified [on bounty creation](https://github.com/AutarkLabs/planning-suite/pull/992/files?file-filters%5B%5D=.json&file-filters%5B%5D=.sol#diff-8130d1a20d069683a6ed33da9ae39fa0R161); that's the user's address, which [will be refunded](https://github.com/AutarkLabs/planning-suite/pull/992/fil …
> [#926] killBounty support

- apps/projects/app/App.js
- apps/projects/app/components/Content/Settings.js
- apps/projects/app/components/Panel/FundIssues/FundIssues.js
- apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
- apps/projects/app/components/Panel/SubmitWork/SubmitWork.js
- apps/projects/app/hooks/useGithubAuth.js
App.js does not need `githubCurrentUser`, so there's no reason to fire the `useEffect` hook and its background request to GitHub on initial page load. This allows us to simplify the hook and only return `githubCurrentUser`, instead of also returning `client`.
In addition, this also improves the custom hook itself:
* only run the effect if `token` is defined; return early otherwise
* since `setClient` fires asynchronously, `client` is not immediately defined; this caused 401 errors
Note that every component that needs this hook will re-fire the `useEffect` function; they are not sharing global state for `githubCurrentUser`. If the user opens many of the panels & pages that need `githubCurrentUser`, this wastes their bandwidth. On slow connections, this could become problematic. We may …
> Projects: improve useGithubAuth hook

- apps/discussions/app/modules/Comment.js
- apps/discussions/app/modules/CommentForm.js
For some reason the `aria-live` elements here seem to get registered twice, at least by Voice Over. This causes the updated content to be read twice.
* Click "Delete", Voice Over speaks out "Confirm delete; Confirm delete"
* Click "Edit", Voice Over speaks out the new card contents, then at the end says "Cancel; Cancel"
* Click "Cancel", Voice Over speaks out "Confirm Cancel; Confirm Cancel"
I was unable to determine why this happens. The most relevant information I found is a slightly different problem affecting nvda, a different screen reader: https://github.com/nvaccess/nvda/issues/7996
Having spent an hour or so researching this problem, I decided to punt on it for now. The new interaction is still more understandable than the old, when using a screen reader; the double-reading seems …
> Discussions: address some accessibility concerns

- README.md
README.md changes:
* Pointed people to https://www.autark.xyz/apps for install instructions
* Added release status
* Removed flow diagram which seemed inconsistent with ultimate implementation
* Removed design concepts (no longer concepts, instead the autark.xyz/apps url has the screenshots)
* Renamed the TPS to Open Enterprise and mentioned it's pending Github URL change
* Added details on the three grants we won
> Cleaned up the readme

- package.json
These hooks are very time-costly and have some unintended side effects. I think the linting hook is a great idea and should remain, but the others should be removed for the time being
> chore/remove husky pre-push and post-checkout hooks

- apps/discussions/README.md
We need the default exports, not named exports, as seen in #1182
> Discussions: fix typos in README examples

- apps/discussions/arapp.json
- apps/planning-suite-kit/contracts/PlanningKit.sol
- This iteration is intended to be open for everyone
- Role was remove from arapp.json
- Permission setup wiped from the PlanningKit template
- ACL variable does not need to be passed to the createDiscussionApp anymore
cc: @Schwartz10
> Remove partial ACL guards on discussions:

- apps/dot-voting/contracts/test/mocks/DotVotingMock.sol
Reverts c455c190a730a6f96a15b76b5fd6af9929d2318c
We [thought][1] we did not need this change, but tests are failing without it.
[1]: https://github.com/AutarkLabs/open-enterprise/pull/1196#pullrequestreview-283984650
> Revert "Revert isValuePct to pure function at DotVotingMock"

- apps/allocations/app/components/App/Accounts.js
- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Card/Empty.js
In this PR, the `if no entries` logic is consolidated into the `App` component.
Previously, the `Empty` card was displayed inside `Accounts` whenever the number of accounts was zero. Now, since `Header` is an element at the same level of `Accounts`, the logic for displaying the `Empty` card, along with hiding the `Header` was moved up to their parent component, `App`. This is similar to what I did for Address Book. See the related discussion [here](https://github.com/AutarkLabs/open-enterprise/pull/1194#pullrequestreview-281662871).
> Allocations: Remove header on No budget page

- apps/address-book/app/api-react.js
- apps/address-book/app/index.js
- apps/allocations/app/api-react.js
- apps/allocations/app/index.js
- apps/dot-voting/app/api-react.js
- apps/dot-voting/app/index.js
- apps/projects/app/api-react.js
- apps/projects/app/index.js
- apps/rewards/app/api-react.js
- apps/rewards/app/index.js
- apps/shared/test-helpers/ganache-cli.sh
- shared/api-react/index.js
This broke with the incorrect addition of the `npm run frontend` script (https://github.com/AutarkLabs/open-enterprise/pull/1109)
> Fix `npm run start:dev`

- apps/allocations/package.json
- apps/projects/package.json
- lerna.json
This is a simple PR that:
- Removes nonexistent `@tps/ui` dependency (since this folder is not still being built as an usable package)
- Disables this pseudo-package from `lerna`, since it was spending a precious time installing its dependencies.
In the future, if there is a consensus, we can make this a proper package and be built with `rollup`, `babel` or `parcel` to be re-usable by other aragon apps, even published into npmjs. At this moment is just a path where we put some shared files.
> [chore] Disable @tps/ui dependencies installation when running `npm i`

- .gitignore
This is a simple PR that ignores intermediate generated `package-lock.json` files by adding them to `.gitignore` since we are not committing them currently
> [chore] Ignore intermediate package-lock.json files

- apps/allocations/app/components/Panel/NewBudget.js
We're in a halfway state right now. We don't have new contracts yet, but we're starting to get new UI.
This keeps the new UI working with the current contracts.
The comparison of a raw JS Number object with `MIN_AMOUNT`, which is a `BigNumber`, was also failing intermittently.
> Allocations: fix creating new account/budget

- apps/dot-voting/app/api-react.js
Calling `window.api.createVote()` broke when the args were put into an
object. This fixes it.
> Dot Voting/stubbedAPI: fix createVote with no args

- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Panel/NewAllocation.js
At some point recently we started getting an error when trying to create an allocation:
Uncaught (in promise) Error: invalid number value (arg="_amount", coderType="uint256", value=1000000000000000000)
The `String(balance)` fixes this issue, but another error hid behind it:
Uncaught (in promise) Error: invalid address (arg="_token", coderType="address", value=undefined)
The initialization of tokenAddress fixes this problem.
Now creating allocations works again. Hooray!
> Fix creating Allocations/Dot Votes

- apps/dot-voting/app/components/VoteDetails/CastVote.js
- apps/dot-voting/app/components/VoteDetails/index.js
- apps/dot-voting/app/components/VotingCard.js
- apps/dot-voting/app/utils/useUserVoteStats.js
It looks like we were sort of doing too much in an effort to get around the slider issues, BigNumber type issues, and the like. I've tested this with multiple values that add up to 100, multiple values that don't add up to 100, values of 100 with a value of 0, a single value of 100, a single non-100 value and they all seem to work.
Main issue seemed to have been either not presenting a BigNumber value, or presenting an exponential value and running into problems around the ether.js parser. Right now it just leverages a BigNumber library, does the calculation using that, and spits out a non exponentiated string value which works well with web3.
> Dv supports value fix

- apps/dot-voting/contracts/DotVoting.sol
I cleaned up some of the language for the DotVoting.sol radspec
Notes: 
- We should clean up some comments around line 457-458
- Can we use a conditional operator of sorts for `addCandidate` so it only shows the metadata part if it's not empty? e.g.:
``` Add voting option "`_description`" to dot vote #`_voteId` `_metadata.isEmpty ? '' : '( `_metadata`)' ` ```
> Enhanced Dot Voting radspec

- apps/projects/app/store/init.js
`cachedState` now starts off, on the first run, as `null`. The attempt to set the default param does not work, though, because the value is intentionally set, not missing. So instead of defaulting within the argument signature, we need to set the default at the first place where we update our cache.
> Projects: fix initialState

- apps/projects/app/components/Panel/NewIssueCuration/NewIssueCuration.js
- apps/projects/app/components/Panel/NewProject/RepoSelector.js
- apps/projects/app/store/events.js
- apps/projects/app/store/helpers/issues.js
See commits for full details.
The main event here is cleaning up `updateIssueDetail`, which was receiving the entire `action` object just so it could use `repoId` and `issueNumber`. It turns out it could already get these values from the first argument passed in.
This PR also fixes `addRepo` and `curateIssues`. These changes are needed to get Projects working with the new client.
> Projects: clean up updateIssueDetail (and more!)

- apps/projects/app/components/Card/Issue.js
- apps/projects/app/components/Panel/RequestAssignment/RequestAssignment.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
- apps/projects/app/components/Panel/SubmitWork/SubmitWork.js
* add `toPromise()` where needed
* fix PropTypes declaration
We probably don't want to merge this into `dev`, as it will presumably be rendered obsolete by incoming Design System and Web3 updates.
However, if one needs to test current behavior on `dev` (as I did), then this branch may be useful.
> Projects: get dev working

- apps/address-book/app/components/Form/Form.js
- apps/address-book/app/components/Panel/NewEntity.js
This implement a new on-time validation on Address book app!
This is based on PR #1245, so please merge it first to see the change. 
- This adds on-time validation on the NewEntity Panel of the Address book.
- This adds a custom entity type on the same panel.
**Remarks**:
- The exact behaviour wasn't specified, so the system is taking the first error and showing it below the submit button.
- There is tons of logic to DRY up between the two different forms. We might want to integrate something like Final Forms into aragon-ui to abstract and uniform validation logic out of the forms. 
See https://youtu.be/m5qysCQm4Mg for a DEMO
**Edited**:
- We deleted the whole `touched` logic to better match with design decision. 
- Also, it have been rebased against `dev`. 
New demo: …
> Address book new entity

- apps/planning-suite-kit/contracts/PlanningKit.sol
This address changes depending on the content of our contracts and the order in which they are deployed. This is accurate for running `npm run publish:http` right now.
Until we get the new template in, which supports making this value a variable, we will need to keep making PRs like this when new contracts get merged.
> PlanningKit.sol: update hard-coded StandardBounties address

- apps/projects/.eslintrc.js
Eslint complains without the `**` at the beginning.
> Projects: fix eslint configuration

- apps/projects/app/components/Content/Settings.js
- apps/projects/app/components/Panel/FundIssues/FundIssues.js
The problem: Every time you type a character in a field in this FundIssues panel, focus on the input is removed, and you have to click back into it to keep typing.
The cause: when you call `setDescription` (or similar), the state changes and the component rerenders. Since `FundForm` is defined within the parent component, this means it gets redefined, and re-rendered to the DOM in its initial state.
The solution: move the definition of `FundForm` outside of the `FundIssues` component.
Taking it further: there's probably extra cleanup we could do here, where state is now defined and managed from FundIssues just so it can be passed through as a prop to FundForm. This could be removed from FundIssues and managed directly within FundForm. For the sake of moving quickly, I did not do this …
> Projects: fix focus events in FundIssues

- apps/projects/app/App.js
In order for aragonUI to load in correct fonts, the content must be wrapped in the `<Main>` component.
> Projects: fix empty-state fonts

- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
New aragonUI uses the `mode` property instead of `emphasis`.
We also don't need to set anything to `secondary`/`normal`, because the buttons are already disabled when the user cannot submit the form.
> Projects: use red/green buttons for review panels

- apps/projects/app/store/events.js
- apps/projects/app/store/init.js
This improves the performance of our app in general, but is crucial now
that we listen to all events from the StandardBounties contract. We want
to ignore all of these events, leaving state unchanged.
We could improve this even further, as shown in the `github` handlers.
We only need to mutate the specific branch of our state tree that
requires updating, and then React's algorithm that calculates whether it
needs to render only gets calculated for the components that make use of
that specific branch. However, this gets us past the bottleneck
introduced by full-state-rewrites-on-every-event-from-StandardBounties
bottleneck, and that's the main improvement we need right now.
> Projects/script: don't update state unnecessarily

- apps/dot-voting/app/components/VotingOption.js
For Dot Votes created from Projects, the options will be regular text.  This displays them as such, while leaving options from Allocations displayed as identity badges.
This also fixes an issue where long issue titles would take up multiple lines in VoteCard, breaking the layout.
> Dot Voting: display label as text when not address

- apps/projects/app/components/Panel/FundIssues/FundIssues.js
If you go to Projects -> Settings and choose to fund bounties with your DAO-specific token, this updates the FundIssues logic to actually support that choice.
> Projects: support funding issues with DAO token

- apps/projects/app/store/events.js
When you sign in with GitHub and then refresh your browser page, this ensures that you're still signed in.
> Projects: cache GitHub authentication

- apps/projects/app/utils/github.js
If this param is not provided, GitHub redirects to whatever we set as our Authorization Callback URL at https://github.com/organizations/AutarkLabs/settings/applications/953918
Removing the param from this URL gives us more flexibility.
> Projects/oauth: remove redirect_uri

- apps/projects/app/api-react.js
Our frontend stubbing for Projects broke when we merged #1109. This fixes it again.
> Projects/stubbedAPI: handle `trigger`

- templates/open-enterprise/contracts/BaseCache.sol
- templates/open-enterprise/contracts/BaseOEApps.sol
- templates/open-enterprise/contracts/OpenEnterpriseTemplate.sol
- Setup Voting as grantee for voting settings permissions (it was ANY_ACCOUNT previously)
- Remove grant from `_transferPermissionFromTemplate` by overloading the function
- Add TokenManager to the cached contract, that allows to:
- Setup TokenManager as grantee for DotVoting and Voting apps
> Fine tune template permissions

- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Panel/NewBudget.js
- apps/allocations/app/store/events.js
* Stop passing `tokens`; calculate it in NewBudget
* Fix finding `editingBudget`
* Rename `onCreateBudget` to `saveBudget`, make it deal with updating as well as creating
* Listen for `SetBudget` event in Allocations background reducer
> Allocations: fix editing budget account

- apps/allocations/app/components/App/App.js
* Don't re-define Wrap on every render. This caused it to be redefined with SidPanel not in it, which is why SidePanel disappeared abruptly rather than slide closed
* Use new state, `panelOpen`, so that contents of SidePanel don't disappear while it closes
> Allocations: close SidePanel smoothly

- templates/open-enterprise/contracts/BaseOEApps.sol
We found that passing in `bytes(0)` for the initializiation payload forces the [AppProxyBase to skip the initialization call](https://github.com/aragon/aragonOS/blob/07d309f5e81c768269dfc49373d41fac4528ebd2/contracts/apps/AppProxyBase.sol#L27) so we set up the address book initialization to be encoded and passed in for installation
> allow address book to initialize on installation

- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Panel/NewAllocation.js
- apps/allocations/app/components/Panel/NewBudget.js
These changes allow users to create allocations for token amounts where the raw value can be bigger than 10e21, before token decimal division
> allow budget and allocation inputs to handle large values (gt 10e21)

- apps/allocations/contracts/Allocations.sol
- make multi-recurrence clause render only if more than one recurrence will generate
- consolidate setMaxCandidates notice to one line so it can be parsed gracefully
> Clean up allocations radspec

- apps/allocations/app/components/Panel/NewAllocation.js
* Simplify markup
* Place text in order that makes most sense for screenreaders; use `flex-direction: column-reverse` for sensible visual design
> Allocations/New: show "Available in Vault"

- apps/allocations/app/components/App/AllocationsHistory.js
Since every amount in this column will always be a debit, we've decided it does not help the user understand anything to shout at them with this bold color.
> Allocations: remove red styling from Amounts

- apps/address-book/app/components/App/App.js
This solves a bug whereby the side panel of Address Book closed abruptly without any animation. It was caused by the introduction of a Wrapper component to simpify the no contacts logic path. I solved it by removing the Wrapper, just like @chadoh did for Allocations in PR #1321.
> Address Book: close sidepanel smoothly

- apps/allocations/package.json
Upgraded AragonUI from 1.0.0-alpha.19 to 1.0.0-alpha.26 in order to improve the styling of the buttons in disabled mode.
> Allocations: AragonUI version bump

- shared/ui/components/form/inputs/LocalIdentitiesAutoComplete.js
- shared/ui/components/form/inputs/RecipientsInput.js
* Remove thick green border on selected item
* Remove extra padding below selected item (believe it or not, that's what the `display: block` is for)
* Fix code style issues identified by linter
> Allocations/Autocomplete: fix visual & code styles

- apps/projects/app/components/Content/Settings.js
Changed the available units for the default work deadline to days, weeks and months. Left the default as it was, which is two weeks. Changed the unit conversion logic to the following:
1. If there's a unit in which the amount of time is an integer, choose that. If there is more than one such unit, choose the longest. So for instance 180 days will be displayed as 6 months.
2. If the amount of time has to be displayed with decimals, then choose the longest unit that's less or equal to half the amount of time to be displayed. So for instance 10.5 days is displayed in days because a week isn't less or equal to 5.25 days.
> Projects: default work deadline in weeks + improved unit conversion logic

- apps/dot-voting/app/components/VotingCard.js
- apps/dot-voting/app/components/VotingOption.js
* Removed padding from Allocations cards
* Added a fixed size to label container so that Issues cards labels have the same height than Allocations cards
* Made the cards smaller by reducing the available description space to two lines of text
> Dot voting: consistent cards

- apps/projects/contracts/Projects.sol
This PR resolves item #1 of the Mainnet UX Audit document:
> Improve radspec (adding project)
> We passed in the repo ID but it seems to be in bytes form vs. the actual ID used by Github.
> 
> 
> Solution (options):
> Remove this from the radspec since it’s not immediately useful
> Show the actual Github ID
> Add a metadata field in the contract that gets populated with the repo name when adding a project. In the future we can have an ‘updateProject’ contract call which allows user to “sync repo name” in the case of when a repo name was updated
This leverages solution #2, showing the actual Github ID (For example MDEwOlJlcG9zaXRvcnkxNzEyMjg2Mjk=)
Not sure that this is informative enough for the user.
> Change projects `_repoId` to use fromHex

- apps/address-book/app/components/Panel/NewEntity.js
Remove custom types from the "type" dropdown menu. This is a temporary measure while this feature gets implemented.
> Address Book: remove custom types

- apps/projects/app/App.js
- apps/projects/app/components/Content/Issues.js
- apps/projects/app/hooks/useShapedIssue.js
- apps/projects/package.json
The main event: **Switch from `Query` higher-order component to `useQuery` hook.**
This required extracting not just one, but _two_ new functional components out of the `Issues` class component. I was hoping for just one, but we need to make sure we don't call the `useQuery` hook unless both `client` and `query` are defined. Since [hooks can't be conditional](https://reactjs.org/docs/hooks-overview.html#rules-of-hooks), the best path forward that I found was to have `IssuesWrap` render `IssuesQuery` only if these two variables are defined. `IssuesQuery`, then, calls `useQuery` and renders the simplified `Issues` component.
Read through the commits in order for deeper explanations of each specific bit of cleanup that was required to make this change.
> Projects: perform Issues query less frequently

- shared/ui/components/assets/components/Empty.js
- shared/ui/components/assets/components/SyncCard.js
The empty svg was causing import issues in Rewards, an App that doesn't
even directly import it. I converted it into a React component and moved
it into the proper folder after doing so, and this seems to have fixed the
issue of the import issue in the Rewards App.js file
> Fix path resolution for the new syncing empty card

- apps/projects/app/App.js
- apps/projects/app/api-react.js
- apps/projects/app/components/Content/Issues.js
- apps/projects/app/components/Content/Overview.js
- apps/projects/app/components/Panel/NewIssue/NewIssue.js
- apps/projects/app/context/DecoratedRepos.js
- apps/projects/app/store/events.js
- apps/projects/app/store/helpers/repos.js
- apps/projects/app/store/init.js
Since we can't be confident that the user is logged in at the time events are read from the blockchain,
And since we can't be sure we'll see these events again due to how aragonAPI's store caching works,
We want everything in the appState reducer (aka script.js) to rely only on blockchain and IPFS data.
This means that the other data in `repos` needs to be loaded in on the frontend, once we know that the user has logged into GitHub.
Note that this architecture uses a `globalDecoratedRepos` variable, defined at the top level of the new `hooks/useRepos` file. This ensures that the first frontend component that needs to decorate repos (which happens to be App.js) will update this file-global variable, and subsequent components that need decorated repos can avoid unnecessary API calls to …
> Projects: stop making GitHub queries in script.js

- apps/rewards/app/utils/metric-utils.js
resolves #1393 
Just added a check to see if rewards are empty.
> Fix calculateMonthlyAvg for empty reward

- apps/address-book/package.json
- apps/allocations/package.json
- apps/discussions/package.json
- apps/dot-voting/package.json
- apps/projects/package.json
- apps/rewards/package.json
- templates/dev/package.json
- templates/open-enterprise/package.json
This small PR adds the option to `publish:http`, that prevents publishing the whole app folder, that will solve 2 main issues:
- The large `apm` package size, that also takes more space in the hard disk
- The extra-time needed to add those files that are not needed to be in the package
Even `aragon-cli` suggests to do so:
In the future I think we should move our publish commands to an external script to have better readability/maintainability and deduplicate a bit, but for now this will help a bit, even in publish:http!
---
The second part of this PR just removes `--all` from every `truffle compile` call, since truffle automatically detects which contract changed to compile again, we are basically overriding this smart behavior to force compiling every contract each time! that is really a …
> Add --files to publish:http scripts

- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Panel/NewBudget.js
It's better to not establish a budget limit to accommodate the use case in which a budget is set for tokens that have not yet been minted. This check is performed in New Allocation in any way.
> Allocations: remove funds limit for New/Edit Budget Panel

- apps/allocations/app/components/App/AllocationsHistory.js
- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/LocalIdentityBadge/IdentityManager.js
- apps/allocations/app/components/LocalIdentityBadge/LocalIdentityBadge.js
- apps/allocations/app/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
- apps/allocations/app/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
Fixes #1375 
I'm copying the LocalIdentityBadge component from Address Book, since Projects and Dot Voting are using an older version of it, which is in `shared`. I'll create a new issue to update that.
--
Fixes #1380 
Now passing the `networkType` to LocalIdentityBadge in order to choose the right network for the address' URL in Etherscan
(when on the private network, the etherscan link is rightfully disabled)
> Allocations: add LocalIdentityBadge in Allocations history

- apps/dot-voting/app/components/VoteCardGroup.js
Fixes #1373 
Fixes #1374 
We want to use the same padding values on wider screens that we do on narrow screens.
Also, there's no reason to make the headings unselectable. I see no benefit of doing so, only potential frustration.
> Dot Voting: fix padding for wider layouts

- apps/projects/app/components/Panel/FundIssues/FundIssues.js
Missed change in #1350, where the shared IssueTitle component was imported into FundIssues, but the old interface was still being used in one spot.
> Projects/FundIssues: fix IssueTitle usage

- apps/address-book/app/components/App/Entities.js
- apps/address-book/app/components/LocalIdentityBadge/LocalIdentityBadge.js
- shared/identity/LocalIdentityBadge.js
Address books `App/Entities.js` now use `forceAddress` property with
<LocalIdentityBadge />.
The implementation have been copied from [Aragon IdentityBadge component](
https://github.com/aragon/aragon/blob/d754535d8487b94a651209464225d8507ae24a67/src/components/IdentityBadge/LocalIdentityBadge.js#L15)
See https://youtu.be/oxeWHqhoSUo for a demo
> Implement `forceAddress` in LocalIdentityBadge #1265

- apps/address-book/package.json
- apps/allocations/package.json
- apps/discussions/package.json
- apps/dot-voting/package.json
- apps/projects/app/App.js
- apps/projects/app/components/Content/Settings.js
- apps/projects/package.json
- apps/rewards/app/components/App/App.js
- apps/rewards/package.json
This version has the official version of frontend triggers, which has a slightly different interface (`emitTrigger` rather than `trigger`)
This also relies on the latest version of the `master` branch of `aragon/aragon`, which uses an updated version of `@aragon/wrapper`.
> Update @aragon/api to latest

- templates/open-enterprise/contracts/OpenEnterpriseTemplate.sol
Helps resolve some audit feedback. When the contracts were rearchitected, some of the radspec wasn't re-written. also removed todos since token manager was added
> Removed TODOs & added radspec for newOpenEnterprise

- apps/rewards/app/components/Panel/NewReward/NewReward.js
Restrict the dates in the New Reward side panel so that they have to be at least tomorrow. Change the default dates to tomorrow.
Since we're not using the `moment` library anymore, I didn't introduce new usages of it. However, I also didn't change the already existing usages in order to deliver this quickly.
Before: the default date was today and it was allowed
After:
**Note**: there was no need to change the error messages since they already restricted the dates to after today.
> Rewards: dates can't be today

- apps/rewards/app/app-state-reducer.js
- apps/rewards/app/components/App/App.js
- apps/rewards/app/components/Content/MyRewards.js
- resolves #1429 
- start date now corresponds to the first disbursement date
- simplified date calculations for new reward submissions
- made recurring reward claiming logic more robust so you can claim multiple recurring rewards from a single row
> Rewards: Recurring Dividends fixes

- apps/allocations/app/components/Card/Budget.js
Fixes #1474
We have a little bit more UX & verification work to do around deactivating budgets. We will get to this soon, so it's not sensible to remove all deactivation logic, but for now we need to remove this option from the Budget context menu.
> Allocations: comment out "deactivate" option

- apps/address-book/app/components/App/Entities.js
- shared/identity/LocalIdentityBadge.js
I noticed [some][1] [minor][2] code style issues in Address Book that I wanted to clean up.
* replace tab with spaces
* get rid of superfluous `={true}`
* simplify variable names
* get rid of intermediate variable
* alphabetize props
* fix "invalid prop type: expected string, got object" error thrown by `Tag`
* change keys to simple numbers – it turns out aragonUI does not require keys at all here, but our linter does. In any case, having all the keys be the same value is not what we want.
[1]: https://github.com/AutarkLabs/open-enterprise/pull/1274#pullrequestreview-305441192
[2]: https://github.com/AutarkLabs/open-enterprise/pull/1418#pullrequestreview-306026325
> Address Book: minor cleanup

- docs/CODEOWNERS
I followed the instructions at https://docs.pullpanda.com/products/assigner/avoiding-team-notifications.  Now only one person will get a notification when Pull Assigner selects them as the reviewer.
> CODEOWNERS: use proxy teams

- apps/dot-voting/app/api-react.js
- apps/dot-voting/app/components/LocalIdentityBadge/LocalIdentityBadge.js
- apps/dot-voting/app/components/LocalIdentityBadge/LocalLabelAppBadge.js
- apps/dot-voting/app/components/VoteDetails/Participation.js
- apps/dot-voting/app/components/VoteDetails/VotingResults.js
- apps/dot-voting/app/components/VoteStatus.js
- shared/api-react/useStubbedApi.js
* add executionTargetData, required since #1326 
* return string for `voteId`, to satisfy `propTypes` expectations
* add resolveAddressIdentity to shared/api-react
* handle some uses of `call`, the lack of which caused noisy warnings
* update imports from `@aragon/api-react` to local stub, which resolves more warnings
> Dot Voting: fix stubbedApi logic

- apps/projects/package.json
Seems to be working well enough, and it's useful to a) use the same version across all of our apps, and  b) follow the latest version - this is alpha, each patch level closer to final release.
> Pushed version of Aragon UI to the latest .32

- apps/dot-voting/app/components/VoteDetails/CastVote/CastVote.js
- apps/dot-voting/app/components/VoteDetails/CastVote/EditVoteOption.js
- apps/dot-voting/app/components/VoteDetails/CastVote/index.js
Rather than only showing the vote value in a grey box that looks like an input field, this uses an actual input field. The amounts can be edited from either the numeric input or the slider.
> Dot Voting: allow voting with number input

- apps/rewards/package.json
A version bump of Rewards' AragonUI in order to implement help bubbles in the New Reward side panel according to the design. In reference to #1466.
The version bump seems to cause no issues. I tested everything according to the Test Script, except claiming rewards, which didn't show up as an option.
> Rewards: AragonUI version bump

- apps/allocations/app/components/Card/Budget.js
Instead of showing the remaining percentage, show the utilized amount in budget cards. Also, remove the amount below limit, and set the font weight to normal.
I also removed an unrelated linting warning.
> Allocations: "utilized" instead of "remaining" in budget cards

- apps/address-book/app/components/App/App.js
- apps/address-book/app/components/Card/Empty.js
- apps/address-book/app/store/events.js
- apps/address-book/app/store/init.js
- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/Card/Empty.js
- apps/dot-voting/app/App.js
- apps/dot-voting/app/store/events.js
- apps/dot-voting/app/store/init.js
- apps/projects/app/App.js
- apps/projects/app/components/Content/Unauthorized.js
- apps/rewards/app/components/App/App.js
- apps/rewards/app/components/Card/Empty.js
- apps/rewards/app/store/events.js
This merge ensures that all apps use caching in their background scripts and display a syncing message while cached events are being loaded. Generally, this means editing 4 files for each app:
app/store/init.js:
- This file sets the initial state with a `isSyncing` variable set to `false`.
- Initializes the state with the `cachedState` if available
app/store/events.js:
- The events file must watch for two events: `SYNC_STATUS_SYNCING` to set `isSyncing = true` and `SYNC_STATUS_SYNCED` to set `isSyncing = false`
app/components/App/App.js:
- The App.js file gets the `isSyncing` variable from the `appState` and passes it to the Empty card. Also, the SyncIndicator component is added to the main screen and is set to visible when `isSyncing == true`
app/components/Card/Empty.js
- This card now …
> Added caching and syncing to apps

- apps/projects/app/components/Card/Issue.js
Added a component that put work details into a separate `<div>` and removes preceding 'dot' if the 'compact' prop is set to true. This way the details wrap nicely onto a new line by setting 'compact' to true on small screen sizes.
> Made work status details arrange dynamically

- apps/dot-voting/app/components/VoteDetails/CastVote/CastVote.js
- apps/dot-voting/app/components/VoteDetails/CastVote/EditVoteOption.js
* allow clearing input
* when clicking away from a cleared input, reset to 0
* also allow typing 0 – this required changing voteAmounts to strings!
* don't permit typing negative numbers
* add (visually-hidden) label, to improve screenreader experience
Also, a DX improvement:
* alphabetize props
> Dot Voting/EditVoteOption: improve number-input UX

- apps/address-book/app/components/App/Entities.js
Fixes #1509
The font colors of type badges were being set with a wrong prop, which
made them be the same purple color instead of the intended
colors. This PR fixes that.
> Address Book: type badges font colors

- apps/rewards/app/components/Panel/NewReward/NewReward.js
With the new dropdown icons, the asset symbols are getting truncated.
The fix here is to make the amount text box flex instead of wide, which
allows the dropdown to be as long as it needs to be, depending on the
number of characters in the symbol
> Rewards: give the asset dropdown panel space

- apps/projects/app/components/Content/Unauthorized.js
- apps/projects/app/components/Panel/NewIssue/AuthorizeGitHub.js
- apps/projects/app/components/Panel/NewIssue/NewIssue.js
- apps/projects/app/store/events.js
- apps/projects/app/store/index.js
- apps/projects/app/utils/github.js
Fixes #1528
* Add help icon explaining why we need GitHub permissions
* At first sign-in, request "no scopes", which gives only read access to public data. This is enough for viewing repositories + their issues, which is enough for most Projects functionality – creating & fulfilling bounties, reviewing bounty submissions, curating issues
* When creating new issues, explain [extra permissions required](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes), and allow user to give more permissions at this time. This is the only Projects action that requires increased permissions.
> Projects: request minimal set of permissions

- apps/rewards/app/store/token.js
- apps/rewards/app/utils/token-utils.js
- shared/store-utils/token.js
In prior versions of web3, the `startBlock` and `transfersEnabled` would not throw when called on ERC20-compliant tokens that weren't Minime tokens. newer versions of web3 now throw errors, which they should, so this change will allow us to catch and handle those errors accordingly.
- resolves #1525 
I also removed that unnecessary log in the shared token-utils lib
> Rewards erc20 fix

- apps/projects/app/store/helpers/tokens.js
Fixes #1437
Under certain conditions, i.e. when a large amount of blocks have been
mined since the last time there was a transaction involving the DAO
token and the browser is refreshed, the DAO token doesn't show up in
the base rate dropdown, under the Settings tab in the Projects app.
This is due to the fact that, under these conditions, the store is
reinitialized and the following function from `store/init.js` gets executed:
const initState = (vaultContract) => async (cachedState) => {
let nextState = await initializeTokens(cachedState || INITIAL_STATE, vaultContract)
[...]
Usually, `cachedState` is null, thus the INITIAL_STATE object is sent
as the first param of `initializeTokens()` from
`store/helpers/tokens.js`, which proceeds then to initialize the
tokens assuming no token exists …
> Projects: fix token initialization issue

- apps/projects/app/components/Content/Settings.js
Issue #1507 
- When you navigate to the Settings page you briefly see a broken image for the avatar
- This fixes the problem by waiting to get the avatar url before displaying the page contents, while waiting it displays the loading message
> Projects: Fix brief display of broken avatar on Settings page

- apps/allocations/app/components/Form/Field/CurrencyBox.js
- apps/allocations/app/components/Panel/NewAllocation.js
- apps/allocations/app/components/Panel/NewBudget.js
When editing a budget, there shouldn't be a dropdown for the currency. Created a new CurrencyBox component that now gets imported by NewAllocations and NewBudget. NewBudget displays CurrencyBox instead of a Dropdown when it is in editing mode.
> Added CurrencyBox to NewBudget.js

- apps/allocations/app/components/Card/Budget.js
editing a budget requires fixing the currecny box so it displays the
right symbol, as well as fixing the radspec so it works as expected
> bugfix: remove budget edits for now

- apps/projects/app/components/Panel/FundIssues/FundIssues.js
- apps/projects/app/utils/math-utils.js
Fixes #1553
* Remove `tokenDetails` and `totalSize`
* Set `tokens` to only the relevant tokens
* Calculate totals within components that need them
* Rework `ErrorMessage` to support new, more complex error text
* Move conditional outside of component
* Move `errorMessages` outside of component definition; use functions for all values for sake of consistency
* Remove some `update`-related logic, as we do not currently (fully) support updating bounties, anyhow. We can fix this logic later.
> Projects/FundIssues: calc totals errors per token

- apps/address-book/.eslintrc.js
- apps/allocations/.eslintrc.js
- apps/dot-voting/.eslintrc.js
- apps/projects/.eslintrc.js
- apps/rewards/.eslintrc.js
- shared/ui/.eslintrc.js
This rule causes all of our linting IDE integrations to move very
slowly, and I think commenting this out for now will enhance our
workflows. Note that I'm only commenting it out because I think it's
very useful when we want to optimize our builds. HOwever, for day-to-day
bugfixing and dev work it's probably not necessary
> chore: remove no-unused-modules rule

- apps/allocations/app/app-state-reducer.js
- apps/allocations/app/components/App/AllocationsHistory.js
- apps/allocations/app/components/App/Payouts.js
- apps/allocations/app/components/Panel/NewAllocation.js
- apps/dot-voting/app/store/votes.js
- apps/rewards/app/app-state-reducer.js
- apps/rewards/app/components/Panel/NewReward/NewReward.js
- apps/rewards/app/store/reward.js
- apps/rewards/app/utils/metric-utils.js
Some token contracts (such as DAI) return a contract address where all
alphabet characters are lowercased during a deposit. This can cause
issues if another event returns the case-sensitive address when doing a
search or filter comparison. Utilizing the addressesEqual function
elminates these issues by comparing the addresses via checksum instead.
This resolves the issues we were seeing in the app-state-reducer where `token.symbol` returns a "cannot find symbol of undefined" error.
This change has been verified to resolve the issues we were seeing with mainnet DAI in rewards, allocations, and related forwarders
> bugfix: utilize addressesEqual function

- templates/dev/contracts/DevTemplate.sol
- templates/open-enterprise/contracts/BaseOEApps.sol
- templates/open-enterprise/contracts/OpenEnterpriseTemplate.sol
The token was deprecated as an intialization parameter in our mainnet
contract work. The `encodeWithSelector` function appears to have just
dropped the unnecessary token arg when creating the initialization
bytecode for the projects contract, so now it's finally getting removed
> chore: remove token from template projects args

- apps/projects/app/components/Panel/FundIssues/EditBounty.js
- apps/projects/app/components/Panel/FundIssues/FundIssues.js
Fixes #1565
* improve wording based on `bountySettings.fundingModel`
* only show after an amount/hours input has blurred
> Projects/FundForm: improve "can't be zero" errors

- apps/rewards/app/components/App/App.js
- apps/rewards/app/components/Content/MyRewards.js
- apps/rewards/app/components/Panel/PanelManager.js
- apps/rewards/app/components/Panel/RewardSummary.js
- apps/rewards/app/components/Panel/ViewReward/ViewReward.js
- apps/rewards/app/components/Styles/Header.js
- apps/rewards/app/utils/helpers.js
**TO DO before merging**
Fixes #1629
> Rewards/ViewReward: add status info

- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Shared/BountyContextMenu.js
Achieved by comparing issue.assignee to connectedAccount from useAragonApi()
Apart from that:
1. Icons used theme.* colors, but theme itself wasn't available. Adding
it required updating all colors.
2. Issues in in-progress state should have had 'View Applications'
option - it got added. "View", because another ticket requests all
"Review"s to be changed to "View"s.
3. Accept/Reject buttons in Review Application panel were broken, screens before/after:
> Show SubmitWork option to issue owner only

- apps/projects/app/components/Panel/FundIssues/FundIssues.js
- apps/projects/app/components/Shared/BountyContextMenu.js
- apps/projects/app/components/Shared/FilterBar/FilterBar.js
Gave sentence case to context menus:
And fixed the language for the message when funding multiple issues where an issue is already funded. Additionally, listing only the funded issues (all issues used to be listed):
Also, Issue #1571 also required that the 'Update funding' option be removed, but that was done on an earlier PR.
> Projects: Context menu sentence case

- apps/rewards/app/store/reward.js
- apps/rewards/contracts/Rewards.sol
*This PR is the product of some awesome team work. @chadoh helped me try to reproduce the issue locally; @stellarmagnet taught me how to inspect the state of a DAO on Rinkeby; @ottodevs generously spent many of his sleeping hours going with me through the steps to publish my
solution to Rinkeby and make it work there; and @topocount debugged an issue with claiming rewards. Thank you all so much!*
On Rinkeby, when a reward is claimed it suddenly disappears from My Rewards, and reappears after switching tabs. Since I was unable to reproduce this on my local environment, I investigated the root cause of this problem and found the following facts:
**F1**. The recently-claimed reward disappears because it gets filtered out from the `myRewards` object by the app state reducer.
**F2**. The app …
> Rewards/store: Fix claimed rewards' disappearance

- apps/projects/app/components/Panel/NewIssue/NewIssue.js
- apps/projects/app/utils/gql-queries.js
* Remove obsolete GET_ISSUES
* Don't use temporary variable
* Restructure getIssuesGQL to make it easier to read
> Projects: cleanup getIssuesForRepos query

- apps/allocations/app/components/Card/Budget.js
- apps/allocations/app/components/Panel/NewBudget.js
- apps/allocations/contracts/Allocations.sol
Third symbol in the dropdown:
Displays correctly when editing budget:
> Allocations: Fix edit budget symbol

- apps/allocations/app/components/Panel/NewAllocation.js
- apps/allocations/app/components/Panel/NewBudget.js
Fix for issue #1584:
Before the panel state would update the INITIAL_STATE const on updates, so anytime the panel state was initialized it would just get the last state instead of a new state.
Also, it should be noted that the 'Edit budget' option has been removed from the context menu. I'm not sure why this was done so I left it that way. Whenever we decide to have an 'Edit budget' again this state problem will be fixed.
> Allocations: New panel gets fresh state

- lerna.json
- package.json
This runs everything in parallel by default, which means we can remove our `--parallel` flags.
This results in much faster startup of our `start:dev` process, at the cost of making machines quite slow while it runs and having somewhat more chaotic logs.
> Remove `concurrency: 1` option from lerna

- apps/projects/app/components/Content/IssueDetail/BountyCard.js
- apps/projects/app/components/Content/IssueDetail/EventsCard.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
- apps/projects/app/components/Panel/usePanelManagement.js
- apps/projects/app/components/Shared/BountyContextMenu.js
A bool variable has been introduced, so links in Activity log
can modify default behavior - which is to show review form
in those panels (unless review had already taken place).
No cleanup was intended here - there is another PR dealing
with Status and Avatar components. This PR is to strictly
add RO mode to the panels.
Screen (work submission, application submission looks pretty much the same):
> Both Review panels can be now read-only

- apps/projects/app/components/Content/IssueDetail/DetailsCard.js
- apps/projects/app/components/Panel/PanelComponents.js
Because all the info now lives in Bounty widget (former Status widget).
Also: cleaned up IssueDetails component - a lot of code was no longer
required. PanelComponents got touched, because Issue Title is a very
reusable component - in all panels, and issue details as well.
What needed to be done was restricting Link to only issue's ID
(it used to be whole div - including GH icon), and adding extra
children prop to the component, so I could do this:
```
<IssueTitleLink issue={issue}>
{dot}
<IconInfo
...
```
as per design. One note: we only download open issues right now.
What happens when an issue a bounty is attached to becomes closed...
That requires a separate ticket.
> Removed bounty info from IssueDetails

- apps/rewards/app/components/Content/Overview.js
Fixes #1614
If there are no future payouts, "Completed" is shown instead.
> Rewards: changed "next payout" to always be in the future

- apps/allocations/app/components/App/Budgets.js
- apps/allocations/app/components/Card/Budget.js
This PR updates Allocations with styling from the [Figma](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=964%3A27). It is based off of this PR: #1759 because that had already implemented some of the style changes. After that PR gets merged I can rebase this PR to the `dev` branch.
> Allocations: Change card style

- apps/allocations/app/hooks/usePathHelpers.js
Named capture groups are still not implemented in Firefox and various mobile browsers
This fixes a bug introduced with the routing in #1758 
You can check that this works by observing that Allocations routing now works in Firefox
> usePathHelpers/parsePath: rm named capture groups

- apps/projects/app/components/Panel/FundIssues/FundIssues.js
Short story: onBlur handler never fires, so setValidate is never set to true, so Submit button is never enabled, as per the screen below. Replacing it with onFocus (as it was before) seems to fix it. I've no information why it got replaced in the first place, so... at least now the form is usable.
> bug fix: setValidate is called onFocus, not onBlur

- apps/projects/app/store/helpers/issues.js
Each Application (request for work on a given issue) had a `status`
field containing text version of the application status: Unreviewed,
Accepted, Rejected. However, because the application was saved
on IPFS in its entirety, including initial Unreviewed status,
it was ignoring further (post-request-review) status changes.
It was not a problem, because we never relied on the status being
correct. We use `review.approved` as the ultimately (and correct)
source of truth.
The choice was between fixing the status field and removing it.
The reasons for choosing to remove it instead of fixing are:
1. There is no analogous field in Work Submission,
2. It's more complicated to fix it - correct way of fixing it
would require not storing it on IPFS == actively removing
it from data we need to store …
> Incorrect status field in Application request

- apps/allocations/app/components/App/App.js
- apps/allocations/app/components/App/BudgetDetail.js
- apps/allocations/app/components/Card/Budget.js
- apps/allocations/app/hooks/usePathHelpers.js
Since it can take quite some time from initial load of an app until the time that it may have enough data loaded to show a certain URL, we do not want to change the route if no matching item is found. Instead, we want to ignore the unknown URL.
This sets us up to do that by making the BudgetDetail component ignore routing, instead passing `budget` in as a prop. This allows all routing logic to be located in the Routes component in App.js.
I also standardized on `usePathHelpers`, rather than sometimes using raw `usePath`.
> Allocations/routing: wait, don't redirect

- apps/allocations/app/components/Panel/NewAllocation.js
The main problem was that we were calculating how to render AmountField even when we didn't actually want to render it, and rendering AmountField requires a budget to be set in order to calculate the Remaining Funds.
This cleans up the render function by moving these inline renders to their own components instead.
> Allocations/NewAllocation: fix when no budget id

- apps/projects/app/components/Panel/PanelComponents.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
- apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
So it can be used in both panels without significant changes.
Status (rejected/approved) is stored in different variables -
WorkSubmissions have variable called 'accepted', the same
variable in Applications is called 'approved'.
> bug fix: Status component used in Review panels updated

- .travis.yml
- shared/deployments/check-publish.sh
- bump aragonCLI CI dep down to 5.6.2 **Note** This is temporary until the wrapper dependencies are fixed in later releases of the CLI
- add in email notifications
> patch Continuous deploy publishing

- apps/allocations/app/utils/helpers.js
* old Chrome: `December 17, 2019 at 4:56:42 PM EST`
* old Firefox: `12/17/2019`
New everywhere: `December 17, 2019, 4:57 PM EST`
(short version: `December 17, 2019`)
Note that this respects the browser's locale. If your browser is in Spanish, you will see: `17 de diciembre de 2019 16:59 GMT-5`
> Allocations: make formatDate support more browsers

- apps/projects/app/components/Content/IssueDetail/EventsCard.js
The generic `index` key was getting passed in and was not recognized by
the (re)view application panel. resolves #1810
> fix: use correct key `requestIndex`

- apps/projects/app/components/Form/Input/DatePicker.js
- apps/projects/app/components/Panel/FundIssues/FundIssues.js
- apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
Issue: if not set, Estimated Date shows up as "Invalid Date". it should be either '-' if not set of correct Date in "month day" format. Screen before:
Screen after:
> fix: corrected Estimated Date in View Application Panel

- apps/projects/app/App.js
- apps/projects/app/hooks/useShapedIssue.js
If a deep-linked issue has a bounty, the app will crash since tokens
often don't load until after all native app state has loaded. This fixes
it by adding in checks for tokens and also sets some default properties
for Tabs that prevent another crash during deep link resolution
> fix: deep-linked issues with bounties crash

- apps/allocations/app/components/Card/Budget.js
The [addition of the aragonUI Link](https://github.com/AutarkLabs/open-enterprise/pull/1758/files?w=1#diff-e811bc466b88a1c9cdb6ad5273ffc7a7R54) caused all elements within the card to inherit the `white-space: nowrap` rule, breaking the line wrapping
> Allocations/Budget Card: wrap title to two lines

- apps/discussions/package.json
- apps/projects/package.json
- shared/ui/components/misc/Markdown.js
* Fix propTypes checks
* Fix link styling
* Update dependency
See "before" screenshot in #1822. Here's how it looks now:
---
I also spent some time researching why our solution formats some text blocks differently than GitHub. Example text block:
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'rewards'
2. Click on 'New Reward.'
3. Scroll down to 'Recurring Dividend'
4. See error once go to the voting and attempt to execute
Here's how GitHub renders this:
Here's how react-markdown renders it:
Note, however, that this is ill-formatted markdown! Well-formatted markdown would put an extra line break below the first and second lines of text, like this:
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'rewards'
2. Click on 'New Reward.'
3. Scroll down to 'Recurring …
> Markdown formatting fixes
